name: Continuous Integration
on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'


jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build --target test --tag todo-app:test .
    - run: docker run --env-file .env.test todo-app:test tests
    - run: docker run --env-file .env.test -e MONGO_DB_CONNECTION_STRING=${{ secrets.MONGO_DB_CONNECTION_STRING }} -e MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }} todo-app:test tests_e2e
  build-docker-image:
    needs: [build]
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: production
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todoapp:latest,${{ secrets.DOCKERHUB_USERNAME }}/todoapp:${{ github.sha }}
  deploy-to-azure:
    needs: [build-docker-image]
    name: Deploy to Azure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release to Azure
        run: curl --fail -dH -X POST '${{ secrets.AZURE_WEBHOOK_URL }}'
